### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by gexinghai** [prymeka/keras-transfer-learning#1]
Hello, I am very interested in your project, could you tell me a brief introduction to your project？

**Comment by prymeka** [comment]
Thank you for your interest. The main purpose of the project is to make the use of the pre-trained Keras CNN models more convenient. The main entry point in the code is the `keras_transfer_learning.build_model` function which takes the name of the Keras model, e.g. `resnet50` (case insensitive) (for a full list of available models you can run `python keras_transfer_learning.py -ln`); input shape (if you would like to use one of the Keras datasets, `(32, 32, 3)` is preferred as MNIST and F-MNIST are automatically reshaped to this shape when using `keras_transfer_learning.load_dataset` function); and a list of layers to be added on top of the base model. You can see entire implementation in the `example.ipynb` notebook. 

At the moment, it seems to me that the code is almost entirely completed. The only part that may change beyond some cosmetic changes is the code related to the loading of Keras datasets. Hope it helps.

**Comment by gexinghai** [comment]
Thanks for your reply, however, I'm still having trouble stomaching all of it. To tell you the truth, I'm not quite in the right position to make sense of your work yet, nor am I entirely qualified to appreciate the full extent of the logics involved in your project, for I am still in my sophomore year. I'm currently enrolled in a intro course for AI fundamentals. We're asked to do a group project on the topic and grab whatever open-source project we can get our hands on, slap it into a moderate state and run it in front of our instructor. The thing is that I don't seem to be able to follow the instructions after the last update. This is as far as i've been able to get:
<img width="1120" alt="Screenshot 2023-04-09 174949" src="https://user-images.githubusercontent.com/55051367/230932920-a5afba89-0fc6-4ddc-8f6d-b6a253f588e5.png">
I know it is too much to ask of you but, can you help us please?

**Comment by prymeka** [comment]
I see. I'm not sure what exactly is the end goal of your project or what's your expertise level but please note that both Tensorflow and Keras are fully open-source.

In case you do not fully grasp the purpose behind Transfer Learning, you might find these articles helpful:
- https://keras.io/guides/transfer_learning/
- https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/
- https://www.tensorflow.org/tutorials/images/transfer_learning

They cover mostly the same information but from slightly different angles. Googling "Transfer Learning" will also give you a ton of other good resources.

The key point is that a model already trained on one dataset (any model, whether its NLP or computer vision, though here I only deal with CNNs) can be retrained to perform well on another dataset in fewer training iterations and with smaller amount of data compared to starting afresh. Keras allows you to download models trained on a large dataset called imagenet (https://www.image-net.org/). These models can then be readily retrained on whatever data you have and perform relatively well -- this is called Transfer Learning. Please refer to the articles linked or to the code to learn more about the steps involved in Transfer Learning. 

If you go to this website:
- https://keras.io/api/applications/

you can see most of the models Keras has available and you can see how to download and use them. If the names of the models don't tell you anything see this article which explains some of them:
- https://towardsdatascience.com/neural-network-architectures-156e5bad51ba

Additionally, I use `tf.data` to create input pipelines for model training. It's not really important to understand them here, it's basically a way of creating iterators over the training data specifically designed for tensorflow, but if you wish to learn more about them you may find these resources helpful:
- https://youtu.be/YrMy-BAqk8k
- https://www.tensorflow.org/guide/data

I'm not sure if this is the answer you were looking for so if you have any specific question about the code or in general don't hesitate to ask.

**Comment by Mccranky83** [comment]
Thank you so much for your lengthy answer! My group can pick up from here with more ease now. Also, apologies for the cluttered cross-commenting on our part🙏
